### ISSUE TITLE
High memory usage with latest version of XMLanguage server

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#234]
Versions

```
Eclipse Wild Web Developer project	XML support using Language Server	0.13.1.202111081705	org.eclipse.wildwebdeveloper.xml

Eclipse.org - m2e	M2E Maven POM File Editor using Wild Web Developer, Lemminx and Maven LS extension (requires Incubating components)	1.18.3.20211116-0804	org.eclipse.m2e.editor.lemminx
```
Running with : java.vendor.version=Temurin-17+35

Opening a pom xml take the memory from 500MB to 6GB within minutes and the whole time the editor is frozen.

**Comment by gayanper** [comment]
Eclipse MAT analysis

Leak suspect 1
![image](https://user-images.githubusercontent.com/7471994/143056831-015783a4-79b5-467e-b194-439bc56a28c5.png)

Leak suspect 2
![image](https://user-images.githubusercontent.com/7471994/143056952-2a6779f1-c9f6-4c97-9d0b-800c6c467bd2.png)

**Comment by mickaelistria** [comment]
Is this with 1 single pom file?

**Comment by gayanper** [comment]
Before the heapdump was taken the heap was at 6GB, but the heapdump caused a full gc which took it down to 2GB

**Comment by gayanper** [comment]
> Is this with 1 single pom file?
Yes this is a single POM file, but there are some BOMs imported into and have considerable amount of dependencies, If you need to i can dump the tree and give you the leaf count. Since the project is proprietary code I will not be able to share it.

**Comment by gayanper** [comment]
The resolved pom has 527 dependency leafs.

**Comment by mickaelistria** [comment]
How does plain Maven like it (or not)? How much RAM it takes when loading this same project?

**Comment by gayanper** [comment]
> How does plain Maven like it (or not)? How much RAM it takes when loading this same project?

Around 1GB even though the used heap is around 600MB

**Comment by gayanper** [comment]
This call seems to be the root cause 
org.eclipse.lemminx.extensions.maven.MavenProjectCache.parseAndCache ()	23,193 ms (99.2%)	23,193 ms (99.2%)

I even hacked the xml server plugin and add max heap size. But still the xml server is really slow and take time to initialize which cause a frozen editor. I also see there are multiple servers hanging in my machine, not sure if they were not properly killed due to this problem.

**Comment by mickaelistria** [comment]
Consuming much RAM can be "normal". Does your workspace contain many Maven projects? Note that LemMinX-Maven will try to load them all at initialization.
What is more intriguing is why would the editor/IDE be frozen. Do you happen to have a jstack about it? It could be that the projects are parsed too early.

**Comment by mickaelistria** [comment]
This is now supposed to be fixed with https://github.com/eclipse/lemminx-maven/pull/235

**Comment by gayanper** [comment]
@mickaelistria will this change be available in m2e snapshots? So i can test it out ?

**Comment by mickaelistria** [comment]
I just merged https://github.com/eclipse-m2e/m2e-core/pull/414 , so next m2e snapshots should include the necessary fix.

**Comment by gayanper** [comment]
Thanks will test it on it

**Comment by gayanper** [comment]
The problem is back with  

M2E - POM Editor using LemMinX language server (includes Incubating components)	1.18.4.20220120-1714

**Comment by gayanper** [comment]
![image](https://user-images.githubusercontent.com/7471994/150559781-616560ff-9057-4647-bf59-5748dcc3193e.png)

few minutes later (actually after uploading the above snippet)

![image](https://user-images.githubusercontent.com/7471994/150559943-77428048-fb99-4d21-addc-b83e26acc3c8.png)

**Comment by mickaelistria** [comment]
I hope https://github.com/eclipse/lemminx-maven/commit/18fb1e5c791435d44d9ce176145622d43556ec1d improves, or even fixes it. It should be available for testing in m2e snapshots within a couple of hours.

**Comment by mickaelistria** [comment]
@gayanper Did you have the opportunity to try latest release, which is part of latest m2e release?

**Comment by mickaelistria** [comment]
OK, so let's close and feel free to open more issues if you see more problems.
